/**
 * Application-wide constants.
 * Eliminates magic strings across the entire codebase.
 */

const ROLES = Object.freeze({
  TEAM_LEADER: "Team Leader",
  DATA_CLEANSING: "Data Cleansing",
});

const ROLE_VALUES = Object.freeze(Object.values(ROLES));

const GROUPS = Object.freeze({
  A: 1,
  B: 2,
});

const GROUP_LABELS = Object.freeze({
  [GROUPS.A]: "Group A",
  [GROUPS.B]: "Group B",
});

const GROUP_VALUES = Object.freeze(Object.values(GROUPS));

const PLANNING_STATUS = Object.freeze({
  ONSITE: "onsite",
  REMOTE: "remote",
});

const LEAVE_REQUEST_STATUS = Object.freeze({
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CANCELLED: "cancelled",
});

const LEAVE_TYPES = Object.freeze({
  ANNUAL: "annual",
  SICK: "sick",
  EXCEPTIONAL: "exceptional",
  UNPAID: "unpaid",
  OTHER: "other",
});

const VALIDATION_STATUS = Object.freeze({
  VALIDATED: "validated",
  PENDING: "pending",
  EXPIRED: "expired",
});

const WORK_SESSION_STATUS = Object.freeze({
  ACTIVE: "active",
  PAUSED: "paused",
  ENDED: "ended",
  EXPIRED: "expired",
});

const AUDIT_ACTIONS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  SELECT_GROUP: "SELECT_GROUP",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  RESTORE_USER: "RESTORE_USER",
  GENERATE_PLANNING: "GENERATE_PLANNING",
  LEAVE_REQUEST_CREATED: "LEAVE_REQUEST_CREATED",
  LEAVE_REQUEST_APPROVED: "LEAVE_REQUEST_APPROVED",
  LEAVE_REQUEST_REJECTED: "LEAVE_REQUEST_REJECTED",
  LEAVE_REQUEST_CANCELLED: "LEAVE_REQUEST_CANCELLED",
  EXPORT_CSV: "EXPORT_CSV",
  EXPORT_XLSX: "EXPORT_XLSX",
  WORK_SESSION_STARTED: "WORK_SESSION_STARTED",
  WORK_SESSION_RESUMED: "WORK_SESSION_RESUMED",
  WORK_SESSION_PAUSED: "WORK_SESSION_PAUSED",
  WORK_SESSION_ENDED: "WORK_SESSION_ENDED",
  WORK_SESSION_EXPIRED: "WORK_SESSION_EXPIRED",
  WORK_HOURS_UPDATED: "WORK_HOURS_UPDATED",
  WORK_SESSION_SUMMARY_VIEWED: "WORK_SESSION_SUMMARY_VIEWED",
});

const VALIDATION_RULES = Object.freeze({
  PASSWORD_MIN_LENGTH: 8,
  MONTH_KEY_REGEX: /^\d{4}-\d{2}$/,
  PLANNING_WINDOW_DAY: 25,
  DEFAULT_WORK_HOUR: 8,
  DEFAULT_ACTUAL_WORK_HOUR: 0,
  SESSION_MAX_AGE_MS: 1000 * 60 * 60 * 8, // 8 hours
  WORK_SESSION_HEARTBEAT_INTERVAL_SECONDS: 60,
  WORK_SESSION_INACTIVITY_SECONDS: 5 * 60,
  WORK_SESSION_HEARTBEAT_GRACE_SECONDS: 120,
  WORK_SESSION_STALE_CLEANUP_INTERVAL_MS: 2 * 60 * 1000,
  WORK_SESSION_MAX_DAILY_SECONDS: 8 * 60 * 60,
  BCRYPT_SALT_ROUNDS: 10,
  AUDIT_LOG_LIMIT: 100,
});

const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
});

module.exports = {
  ROLES,
  ROLE_VALUES,
  GROUPS,
  GROUP_LABELS,
  GROUP_VALUES,
  PLANNING_STATUS,
  LEAVE_REQUEST_STATUS,
  LEAVE_TYPES,
  VALIDATION_STATUS,
  WORK_SESSION_STATUS,
  AUDIT_ACTIONS,
  VALIDATION_RULES,
  HTTP_STATUS,
};
